apiVersion: v2
name: hindsight
description: Hindsight helm chart
type: application
version: 0.2.1
appVersion: "0.2.1"
keywords:
  - ai
  - memory
  - llm
  - agents
maintainers:
  - name: Hindsight Team
